name: pb_live_frontend
description: "A new Flutter project for voice chat room."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  zego_uikit_prebuilt_live_audio_room: ^3.16.10
  zego_uikit: ^2.28.41
  zego_uikit_signaling_plugin: ^2.8.20
  zego_plugin_adapter: ^2.14.2

  flutter_styled_toast: ^2.2.1
  cached_network_image: ^3.4.1
  statemachine: ^3.3.1
  permission_handler: ^12.0.1
  collection: ^1.18.0
  floating: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
